#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
udo apt -y update
sudo apt -y install nginx
sudo chmod -R 777 /var/www/html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx stop
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom.html
sudo sed -i '/server_name _;/a error_page 404 /custom.html;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx start
