#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 4396-web-01 54.91.233.56:80 check\n\tserver 4396-web-02 3.80.32.222:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
