#!/usr/bin/env bash
# bash script that configures a server listening on port 80 of all the server's active IPv4 IPs
sudo service nginx stop
sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i 's/8080 default_server ipv6only=on;/80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default
sudo service nginx start
