#!/usr/bin/env bash
# bad luck 4th good luck 8th Best School other

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	else
		if [ $x -eq 8 ]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
	fi
	(( x++ ))
done
