#!/usr/bin/env bash
# 4th China 9th Japan 17th Italy

x=1
while [ $x -le 20 ]
do
	echo "$x"

	case $x in
		
		4)
			echo "bad luck from China"
			;;
		
		8)
			echo "bad luck from Japan"
			;;
	
		17)
                	echo "bad luck from Italy"
			;;
	esac
	(( x++ ))
done
