#!/usr/bin/env bash
# 4th China 9th Japan 17th Italy

x=1
while [ $x -le 20 ]
do
	echo "$x"
	if [ $x -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $x -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]
        then
                echo "bad luck from Italy"
	fi
	(( x++ ))
done
